### ISSUE TITLE
Column typed with Json gets dropped

### ISSUE THREAD

**Issue by joergjaeckel** [Sukairo-02/drizzle-prisma-generator#1]
Hi,

When I generate the column typed in Prisma schema with "Json" won't be there. Might only be an Uppercase issue because

https://github.com/Sukairo-02/drizzle-prisma-generator/blob/4c1afe717436015aa782c92f8ff491500809eabc/src/util/generators/pg.ts#L30C9-L30C13

**Comment by Sukairo-02** [comment]
Should work with the most recent release
