### ISSUE TITLE
Use of relation name declared in Prisma schema

### ISSUE THREAD

**Issue by joergjaeckel** [Sukairo-02/drizzle-prisma-generator#2]
Is it possible to use the relation name declared in Prisma schema instead of generating named relations like `${aTableName}To${manyTableName}` or `${bTableName}To${manyTableName}`. I think named relations are only needed at both sides for disambiguating relations. 

In Prisma it is 

```
model achievement {
  id                String              @id @default(uuid()) @db.Uuid
  name              String
  description       String
...
  constraints       constraint[]
}
``` 

and for drizzle it turns into 

```
export const achievementRelations = relations(achievement, ({ many }) => ({
	'achievementToconstraint': many(constraint, {
		relationName: 'achievementToconstraint'
	})
}));
```

wich makes it hard to use both in parallel. Wish it would stay `contraints`

**Comment by Sukairo-02** [comment]
Solved, update the package and it should work like that right now.
